### ISSUE TITLE
Ogg xiphComments support

### ISSUE THREAD

**Issue by nikmartin** [vysokyj/tagio#1]
Hello,

I noticed the addition of what might be xiphComments support, but don;t see a test case or docs on the implementation. Does this lib support writing xiphComments to ogg files and if so, do you have an example of how to do it?

**Comment by vysokyj** [comment]
Hello,
sorry for my inactivity.
I just added missing documentation: https://github.com/vysokyj/tagio/blob/develop/doc/flac.md
